spring:
  application:
    name: conference
  profiles:
    active: dev
  sql:
    init:
      mode: always
      schema-location: classpath:/schema.sql
  datasource:
    driverClassName: org.postgresql.Driver
    url:  ${DATASOURCE_URL}
    # url: jdbc:postgresql://localhost:5432/conference
    username: ${DATASOURCE_USERNAME}
    # username: postgres
    password: ${DATASOURCE_PASSWORD}
    # password: changeme
server:
 port: ${PORT}
  # port: 8081

logging:
  level:
    root: DEBUG

